name: CMake
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - uses: actions/checkout@v4
      - name: Install CMake and GCC 13
        run: |
          dnf install -y cmake gcc gcc-c++
      - name: Verify GCC Version
        run: |
          gcc --version
          g++ --version
      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_INSTALL_PREFIX:PATH=/usr/local \
            -DCMAKE_C_COMPILER=/usr/bin/gcc \
            -DCMAKE_CXX_COMPILER=/usr/bin/g++
      - name: Build Project
        run: cmake --build build
      - name: Run Tests
        run: ctest --test-dir build
